# AWSTemplateFormatVersion: '2010-09-09'
# Description: DynamoDB table for contacts

# Parameters:
#   Environment:
#     Type: String
#     Default: dev
#     AllowedValues:
#       - dev
#       - test
#       - prod
#     Description: The deployment environment

# Resources:
#   ContactsTable:
#     Type: AWS::DynamoDB::Table
#     Properties:
#       TableName: !Sub ${Environment}-contacts
#       KeySchema:
#         - AttributeName: lastName
#           KeyType: HASH
#       AttributeDefinitions:
#         - AttributeName: lastName
#           AttributeType: S
#         - AttributeName: email
#           AttributeType: S
#       BillingMode: PAY_PER_REQUEST
#       GlobalSecondaryIndexes:
#         - IndexName: email-index
#           KeySchema:
#             - AttributeName: email
#               KeyType: HASH
#           Projection:
#             ProjectionType: ALL
#       Tags:
#         - Key: Environment
#           Value: !Ref Environment

# Outputs:
#   ContactsTableName:
#     Description: The name of the contacts DynamoDB table
#     Value: !Ref ContactsTable
#   ContactsTableArn:
#     Description: The ARN of the contacts DynamoDB table
#     Value: !GetAtt ContactsTable.Arn

# # CloudFront Distribution for API and Website
#   CloudFrontDistribution:
#     Type: AWS::CloudFront::Distribution
#     Properties:
#       DistributionConfig:
#         Origins:
#           # S3 Origin for Website
#           - DomainName: !GetAtt WebsiteBucket.RegionalDomainName
#             Id: WebsiteOrigin
#             S3OriginConfig:
#               OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}
#           # # S3 Origin for Resumes
#           # - DomainName: !GetAtt ResumeBucket.RegionalDomainName
#           #   Id: ResumeOrigin
#           #   S3OriginConfig:
#           #     OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}
#           # API Gateway Origin
#           - DomainName: !Sub ${ContactApi}.execute-api.${AWS::Region}.amazonaws.com
#             Id: ApiOrigin
#             # OriginPath: !Sub /${Environment}
#             CustomOriginConfig:
#               HTTPPort: 80
#               HTTPSPort: 443
#               OriginProtocolPolicy: https-only
#         Enabled: true
#         DefaultRootObject: index.html
#         DefaultCacheBehavior:
#           AllowedMethods:
#             - GET
#             - HEAD
#             - OPTIONS
#           TargetOriginId: WebsiteOrigin
#           ForwardedValues:
#             QueryString: false
#             Cookies:
#               Forward: none
#           ViewerProtocolPolicy: redirect-to-https
#         CacheBehaviors:
#           # API Path Behavior
#           - PathPattern: /api/*
#             AllowedMethods:
#               - GET
#               - HEAD
#               - OPTIONS
#               - PUT
#               - POST
#               - PATCH
#               - DELETE
#             TargetOriginId: ApiOrigin
#             ForwardedValues:
#               QueryString: true
#               Headers:
#                 - Authorization
#                 - Content-Type
#               Cookies:
#                 Forward: none
#             ViewerProtocolPolicy: https-only
#           # # Resume Path Behavior
#           # - PathPattern: /resumes/*
#           #   AllowedMethods:
#           #     - GET
#           #     - HEAD
#           #     - OPTIONS
#           #   TargetOriginId: ResumeOrigin
#           #   ForwardedValues:
#           #     QueryString: false
#           #     Cookies:
#           #       Forward: none
#           #   ViewerProtocolPolicy: https-only
#         PriceClass: PriceClass_100
#         ViewerCertificate:
#           CloudFrontDefaultCertificate: true
#       Tags:
#         - Key: Environment
#           Value: !Ref Environment

#   CloudFrontOriginAccessIdentity:
#     Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
#     Properties:
#       CloudFrontOriginAccessIdentityConfig:
#         Comment: !Sub ${AWS::StackName} OAI
