AWSTemplateFormatVersion: '2010-09-09'
Description: Deploying vega website

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: The deployment environment

  # ProjectName:
  #     Type: String
  #     Description: "Logical name/prefix for resources"

  TemplateBucket:
    Type: String
    Description: S3 bucket containing CloudFormation templates

  RouteTableId:
    Type: String
    Default: rtb-0bbaaa9146c12d706
    Description: ID of the route table for the VPC endpoin

  VpcId:
    Type: AWS::EC2::VPC::Id
    Default: vpc-03de7ad5a4c7c1822
    Description: ID of the existing company VPC
  
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Default: subnet-02615277a84a5fcb4
    Description: List of existing subnet IDs for deployment

Conditions:
  HasVpcConfig: !Not [!Equals [!Ref VpcId, '']]

Resources:
  # Security Groups Stack
  SecurityGroupsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.amazonaws.com/templates/security-groups.yaml
      Parameters:
        Environment: !Ref Environment
        VpcId: !Ref VpcId
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # Static Website Stack
  StaticWebsiteStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.amazonaws.com/templates/static-website.yaml
      Parameters:
        Environment: !Ref Environment
      Tags:
        - Key: Environment
          Value: !Ref Environment



Outputs:
  # Your outputs will go here

  WebServerSecurityGroupId:
    Condition: HasVpcConfig
    Description: Security Group ID for web servers
    Value: !GetAtt SecurityGroupsStack.Outputs.WebServerSecurityGroupId
    Export:
      Name: !Sub ${AWS::StackName}-WebServerSecurityGroupId

  WebsiteBucketName:
    Description: S3 Bucket for website content
    Value: !GetAtt StaticWebsiteStack.Outputs.WebsiteBucketName
    Export:
      Name: !Sub ${AWS::StackName}-WebsiteBucketName

  WebsiteURL:
    Description: S3 Bucket for website content
    Value: !GetAtt StaticWebsiteStack.Outputs.CloudFrontDistributionDomainName

  CloudFrontDistributionId:
    Description: CloudFront Distribution ID
    Value: !GetAtt StaticWebsiteStack.Outputs.CloudFrontDistributionId

  # CloudFrontDistributionDomainName:
  #   Description: CloudFront Distribution Domain Name
  #   Value: !GetAtt ContactPageStack.Outputs.CloudFrontDistributionDomainName
  #   Export:
  #     Name: !Sub ${AWS::StackName}-CloudFrontDomainName
